/**
 * generate-html.js
 * 生成自包含的 HTML 文件，双击即可在浏览器中查看
 *
 * 提供两种渲染引擎：
 *   - Mermaid 渲染（轻量，适合快速预览）
 *   - simple-mind-map 渲染（功能完整，支持交互）
 */

import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const LIB_SOURCE = path.join(__dirname, "..", "lib", "simpleMindMap.umd.min.js");

/**
 * 转义 HTML 特殊字符
 */
function escapeHtml(str) {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/**
 * 生成 Mermaid 渲染的 HTML（轻量版）
 * 使用 CDN 加载 mermaid.js，双击即可查看
 */
function generateMermaidHtml(title, mapType, mermaidCode) {
  return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)} - VisionMap</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      background: #f5f7fa;
      min-height: 100vh;
      display: flex;
      flex-direction: column;
    }
    .header {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      padding: 20px 32px;
      display: flex;
      align-items: center;
      gap: 12px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.15);
    }
    .header svg { width: 28px; height: 28px; }
    .header h1 { font-size: 20px; font-weight: 600; }
    .header .subtitle { font-size: 13px; opacity: 0.8; margin-left: auto; }
    .content {
      flex: 1;
      display: flex;
      justify-content: center;
      align-items: flex-start;
      padding: 32px;
    }
    .mermaid-wrapper {
      background: white;
      border-radius: 12px;
      padding: 32px;
      box-shadow: 0 4px 24px rgba(0,0,0,0.08);
      max-width: 100%;
      overflow-x: auto;
    }
    .footer {
      text-align: center;
      padding: 12px;
      color: #999;
      font-size: 12px;
    }
  </style>
</head>
<body>
  <div class="header">
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
      <circle cx="12" cy="12" r="10"/>
      <path d="M12 2a10 10 0 0 1 0 20"/>
      <circle cx="12" cy="8" r="2" fill="currentColor"/>
      <circle cx="8" cy="14" r="2" fill="currentColor"/>
      <circle cx="16" cy="14" r="2" fill="currentColor"/>
    </svg>
    <h1>${escapeHtml(title)}</h1>
    <span class="subtitle">Generated by VisionMap</span>
  </div>
  <div class="content">
    <div class="mermaid-wrapper">
      <pre class="mermaid">${escapeHtml(mermaidCode)}</pre>
    </div>
  </div>
  <div class="footer">VisionMap &copy; ${new Date().getFullYear()} | Powered by simple-mind-map</div>
  <script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
  <script>
    mermaid.initialize({
      startOnLoad: true,
      theme: 'default',
      securityLevel: 'loose',
      mindmap: { padding: 16 },
      flowchart: { curve: 'basis', padding: 16 }
    });
  </script>
</body>
</html>`;
}

/**
 * 递归生成 simple-mind-map 的节点数据
 */
function treeToMindMapData(node) {
  return {
    data: {
      text: node.text,
      richText: true,
      expand: true,
    },
    children: (node.children || []).map(treeToMindMapData),
  };
}

/**
 * 生成 simple-mind-map 渲染的 HTML（完整交互版）
 * 使用 CDN 加载 simple-mind-map
 */
function generateFullHtml(title, mapType, jsonData) {
  // MindMap 的 data 参数需要 root 节点树，不是完整的 JSON 对象
  const rootData = jsonData.root || jsonData;
  const dataJson = JSON.stringify(rootData).replace(/</g, "\\u003c");

  return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)} - VisionMap</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      background: #f5f7fa;
      height: 100vh;
      display: flex;
      flex-direction: column;
      overflow: hidden;
    }
    .header {
      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
      color: white;
      padding: 16px 32px;
      display: flex;
      align-items: center;
      gap: 12px;
      box-shadow: 0 2px 8px rgba(0,0,0,0.15);
      flex-shrink: 0;
    }
    .header h1 { font-size: 18px; font-weight: 600; }
    .header .subtitle { font-size: 13px; opacity: 0.8; margin-left: auto; }
    .toolbar {
      background: white;
      padding: 8px 16px;
      display: flex;
      gap: 8px;
      border-bottom: 1px solid #e8e8e8;
      flex-shrink: 0;
    }
    .toolbar button {
      padding: 6px 14px;
      border: 1px solid #d9d9d9;
      border-radius: 4px;
      background: white;
      cursor: pointer;
      font-size: 13px;
      transition: all 0.2s;
    }
    .toolbar button:hover {
      border-color: #667eea;
      color: #667eea;
    }
    #mindmap-container {
      flex: 1;
      position: relative;
      overflow: hidden;
    }
    .footer {
      text-align: center;
      padding: 8px;
      color: #999;
      font-size: 11px;
      flex-shrink: 0;
    }
    .tips {
      position: absolute;
      bottom: 16px;
      left: 16px;
      background: rgba(0,0,0,0.6);
      color: white;
      padding: 8px 14px;
      border-radius: 6px;
      font-size: 12px;
      line-height: 1.8;
      z-index: 10;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>${escapeHtml(title)}</h1>
    <span class="subtitle">VisionMap | 可交互思维导图</span>
  </div>
  <div class="toolbar">
    <button onclick="zoomIn()">🔍 放大</button>
    <button onclick="zoomOut()">🔍 缩小</button>
    <button onclick="fitView()">📐 适应窗口</button>
    <button onclick="expandAll()">📂 全部展开</button>
    <button onclick="collapseAll()">📁 全部折叠</button>
    <button onclick="exportImage()">📸 导出图片</button>
  </div>
  <div id="mindmap-container"></div>
  <div class="tips">
    💡 滚轮缩放 | 拖拽移动 | 双击节点编辑 | 右键菜单操作
  </div>
  <div class="footer">VisionMap &copy; ${new Date().getFullYear()} | Powered by simple-mind-map</div>

  <script src="lib/simpleMindMap.umd.min.js"></script>
  <script>
    const MindMap = simpleMindMap.default || simpleMindMap;
    const data = ${dataJson};

    let mindMap = null;
    try {
      mindMap = new MindMap({
        el: document.getElementById('mindmap-container'),
        data: data,
        layout: '${mapType === "orgchart" ? "organizationStructure" : mapType === "fishbone" ? "fishbone" : mapType === "logicalStructure" ? "logicalStructure" : "mindMap"}',
        theme: 'default',
        enableFreeDrag: true,
        errorHandler: (type, err) => {
          console.warn('VisionMap:', type, err);
        },
      });

      // 暴露全局操作
      window.zoomIn = () => mindMap && mindMap.view.enlarge();
      window.zoomOut = () => mindMap && mindMap.view.narrow();
      window.fitView = () => mindMap && mindMap.view.fit();
      window.expandAll = () => mindMap && mindMap.expandAll();
      window.collapseAll = () => mindMap && mindMap.collapseAll();
      window.exportImage = () => {
        if (mindMap) {
          mindMap.export('png', true, 'visionmap').then(() => {
            alert('图片已导出');
          }).catch(err => {
            alert('导出失败: ' + err.message);
          });
        }
      };
    } catch (e) {
      document.getElementById('mindmap-container').innerHTML =
        '<div style="padding:40px;text-align:center;color:#999;">' +
        '<h2>加载失败</h2><p>' + e.message + '</p>' +
        '<p>请确保网络连接正常（需要加载 CDN 资源）</p></div>';
    }
  </script>
</body>
</html>`;
}

/**
 * 主函数：生成 HTML 文件
 * @param {string} title - 标题
 * @param {string} mapType - 导图类型
 * @param {object} jsonData - simple-mind-map 格式的 JSON 数据
 * @param {string} outputDir - 输出目录（用于复制 lib 文件）
 * @returns {string} HTML 内容
 */
export async function generateHtml(title, mapType, jsonData, outputDir) {
  // 优先生成完整交互版（使用 simple-mind-map）
  if (jsonData && jsonData.root) {
    // 复制 lib 文件到输出目录
    const outDir = outputDir || path.join(process.cwd(), "output");
    const libDir = path.join(outDir, "lib");
    await fs.mkdir(libDir, { recursive: true });
    const libTarget = path.join(libDir, "simpleMindMap.umd.min.js");
    try {
      await fs.copyFile(LIB_SOURCE, libTarget);
    } catch (e) {
      console.error("复制 lib 文件失败:", e.message);
      console.error("源文件:", LIB_SOURCE);
      console.error("目标:", libTarget);
    }
    return generateFullHtml(title, mapType, jsonData);
  }

  // 降级到 Mermaid 版（轻量预览）
  const { generateMermaid } = await import("./generate-mermaid.js");
  const mermaidCode = await generateMermaid(title, mapType);
  return generateMermaidHtml(title, mapType, mermaidCode);
}
